# -*- coding: utf-8 -*-
"""Train.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1H9j56rCz5LAxAdsJAT3PwozbosVmz5DN
"""

import os
os.environ["TF_USE_LEGACY_KERAS"] = "1"
import numpy as np
import cv2
from PIL import Image
import os
import matplotlib.pylab as plt
import tensorflow as tf
import tensorflow_hub as hub
from tensorflow import keras
from tensorflow.keras import layers
from tensorflow.keras.models import Sequential

from google.colab import drive
drive.mount('/content/drive')
!unzip "/content/drive/MyDrive/archive_resized.zip" -d "/content/"

Data_dir='archive_resized'
Img_size=(224,224)

import pathlib
data_dir = pathlib.Path(Data_dir)
data_dir

waste_images_dict = {
    'battery': list(data_dir.glob('battery/*')),
    'biological': list(data_dir.glob('biological/*')),
    'cardboard': list(data_dir.glob('cardboard/*')),
    'clothes': list(data_dir.glob('clothes/*')),
    'glass': list(data_dir.glob('glass/*')),
    'metal': list(data_dir.glob('metal/*')),
    'paper': list(data_dir.glob('paper/*')),
    'plastic': list(data_dir.glob('plastic/*')),
    'shoes': list(data_dir.glob('shoes/*')),
    'trash': list(data_dir.glob('trash/*'))
}
waste_labels_dict = {
    'battery': 0,
    'biological': 1,
    'cardboard': 2,
    'clothes': 3,
    'glass': 4,
    'metal': 5,
    'paper': 6,
    'plastic': 7,
    'shoes': 8,
    'trash': 9
}

X, y = [], []
for waste_name, images in waste_images_dict.items():
    for image in images:
        img = cv2.imread(str(image))
        X.append(img)
        y.append(waste_labels_dict[waste_name])

X = np.array(X)
y = np.array(y)

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=0)

feature_extractor_model = "https://tfhub.dev/google/tf2-preview/mobilenet_v2/feature_vector/4"
pretrained_model_without_top_layer = hub.KerasLayer(
    feature_extractor_model, input_shape=(224, 224, 3), trainable=False)

num_of_categories = 10
model = tf.keras.Sequential([
  tf.keras.layers.Rescaling(1./255, input_shape=(224, 224, 3)),
  pretrained_model_without_top_layer,
  tf.keras.layers.Dense(num_of_categories)
])

model.summary()

model.compile(
  optimizer="adam",
  loss=tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True),
  metrics=['accuracy']
)

model.fit(X_train, y_train, epochs=5)

model.evaluate(X_test,y_test)

model.save('waste_model_v1')